export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const Apikey = "18566c86";

export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';
export const FETCH_MOVIE_DETAIL_REQUEST = 'FETCH_MOVIE_DETAIL_REQUEST';
export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';
export const FETCH_MOVIE_DETAIL_ERROR = 'FETCH_MOVIE_DETAIL_ERROR';


export const FILTER_MOVIE_BY_TITLE = 'FILTER_MOVIE_BY_TITLE';
export const FILTER_MOVIE_BY_YEAR = 'FILTER_MOVIE_BY_YEAR';
export const FILTER_MOVIE_BY_TYPE = 'FILTER_MOVIE_BY_TYPE';

export const LOAD_MORE_RESULT = 'LOAD_MORE_RESULT';